export enum identifiers {
  EVENT_LOG_SUCCESS = 'EVENT_LOG_SUCCESS',
  EVENT_LOG_ERROR = 'EVENT_LOG_ERROR',
  USER_FETCH_SUCCESS = 'USER_FETCH_SUCCESS',
  USER_ADD_SUCCESS = 'USER_ADD_SUCCESS',
  USER_ADD_FAILURE = 'USER_ADD_FAILURE',
}
