const tableNames = {
  NAVIGATION: 'analytics-navigation',
  USERS: 'analytics-users',
  RECURRING: 'analytics-recurring',
};

const columns = {
  users: {
    visitorID: 'visitorID',
    user: 'user',
    uid: 'uid',
    asn: 'asn',
    city: 'city',
    continent_code: 'continent_code',
    country: 'country',
    country_area: 'country_area',
    country_calling_code: 'country_calling_code',
    country_capital: 'country_capital',
    country_code: 'country_code',
    country_code_iso3: 'country_code_iso3',
    country_name: 'country_name',
    country_population: 'country_population',
    country_tld: 'country_tld',
    csrfToken: 'csrfToken',
    currency: 'currency',
    currency_name: 'currency_name',
    fp_OS: 'fp_OS',
    fp_OSVersion: 'fp_OSVersion',
    fp_Visitor: 'fp_Visitor',
    fp_accuracyRadius: 'fp_accuracyRadius',
    fp_browserName: 'fp_browserName',
    fp_browserVersion: 'fp_browserVersion',
    fp_cityName: 'fp_cityName',
    fp_confidenceScore: 'fp_confidenceScore',
    fp_continentCode: 'fp_continentCode',
    fp_continentName: 'fp_continentName',
    fp_country: 'fp_country',
    fp_countryCode: 'fp_countryCode',
    fp_device: 'fp_device',
    fp_firstSeenAt_global: 'fp_firstSeenAt_global',
    fp_firstSeenAt_subscription: 'fp_firstSeenAt_subscription',
    fp_incognito: 'fp_incognito',
    fp_ip: 'fp_ip',
    fp_latitude: 'fp_latitude',
    fp_longitude: 'fp_longitude',
    fp_metaVersion: 'fp_metaVersion',
    fp_postCode: 'fp_postCode',
    fp_subDivision: 'fp_subDivision',
    fp_timezone: 'fp_timezone',
    in_eu: 'in_eu',
    ip: 'ip',
    languages: 'languages',
    lastModified: 'lastModified',
    latitude: 'latitude',
    longitude: 'longitude',
    network: 'network',
    org: 'org',
    postal: 'postal',
    region: 'region',
    region_code: 'region_code',
    timezone: 'timezone',
    totalVisits: 'totalVisits',
    ua: 'ua',
    utc_offset: 'utc_offset',
    version: 'version',
  },
  navigation: {
    visitorID: 'visitorID',
    viewName: 'viewName',
    viewedAt: 'viewedAt',
  },
};

export { tableNames, columns };
