@BASE_URL=http://localhost:4200

GET {{BASE_URL}}/dev/get-firebase-collection?collectionName=prod-geoAnalytics
###
GET {{BASE_URL}}/dev/migrate-from-firebase-collection?collectionName=prod-geoAnalytics
